
version: '3'
services:
  migrate:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 info migrate
    volumes:
      - ${PWD}/sql:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
